#!/bin/bash

sudo apt update && sudo apt install -y python3-pip
pip install jupyterlab

cat >>~/.bashrc <<EOF
export PATH="\$PATH:~/.local/bin"
EOF

# PATH is ignored by the command passed to docker, so make sure jupyter is accessible
sudo ln -s ~/.local/bin/jupyter /usr/local/bin
